version: "3.8"

services:

  axon-server:
    image: axoniq/axonserver
    ports:
      - 8024:8024
      - 8124:8124

  mariadb:
    image: bitnami/mariadb:10.11
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_USER=user
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=bankt_query_db
