server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mariadb://user:password@localhost:3306/bankt_query_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

axon:
  serializer:
    messages: jackson
    general: jackson
    events: jackson


logging:
  level:
    org.apache.kafka: OFF
    org.springframework.kafka: WARN
