server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:mysql://root:password@localhost:3306/bankt-query-db?createDatabaseIfNotExist=true
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  datasource:
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    username: root
    password: techbankRootPsw
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
